### ISSUE TITLE
Depricated?

### ISSUE THREAD

**Issue by IanMunster** [JarlPenguin/BeCyIconGrabberPortable#1]
Dear JarlPenguin,

From your repository I saw that your tool BeCyIconGrabber is now deprecated, is there a tool that has continued development?
Also, I've used your tool a few times and it seems to work perfectly fine, is there a reason why this tool is deprecated? And if so, do you recommend another tool? If so, what tool?

Thanks in advance and for your hard work!
Cheers,
Ian

**Comment by JarlPenguin** [comment]
Hey there, sorry for the (very) late reply!

> is there a reason why this tool is deprecated?

The original upstream tool hasn't been updated in years (this repo just serves as a wrapper for it), hence it being deprecated. I also don't have the time to maintain this anymore.

> And if so, do you recommend another tool? If so, what tool?

This one should still work fine, so I'd keep on using it. I'm not aware of any alternatives (haven't researched).
